function init(self)
	self.toggle = true
	msg.post('.', 'acquire_input_focus')
end

function final(self)
	msg.post('.', 'release_input_focus')
end

function on_input(self, action_id, action)
	if action.pressed and action_id == hash('space') then
		self.toggle = not self.toggle
		if self.toggle then
			msg.post("#win_screen", "enable")
		elseif not self.toggle then
			msg.post("#win_screen", "disable")
		end
	end
end